### ISSUE TITLE
Very few presets are set to be compatible with BBL A1 Mini

### ISSUE THREAD

**Issue by akoebbe** [DRIgnazGortngschirl/bambulab-studio-orca-slicer-presets#5]
I pulled in all the filament presets in to Orca, but only 2 showed up (with the inherits folder in place). I just realized that the inherits presets are only set to be compatible with BBL X1, X1C, and P1S while I have an A1 Mini. Is it intended for this repo to only be compatible with only X1, X1C, and P1S, or do the other BBL printers need to be added to the `compatible_printers` list in the parent presets?

**Comment by DRIgnazGortngschirl** [comment]
Hello @akoebbe,

I originally started this repository for the BBL X1C, but since then, I have expanded its scope a bit. Feel free to try adding "compatible_printers" in the presets and test them to see if they work for you. I would greatly appreciate it if you could also add any filaments that work for you to the collection or provide feedback. This will help me refine some aspects. Additionally, I'll be adding the A1 Mini to the list of compatible printers if these work for you.

**Comment by DRIgnazGortngschirl** [comment]
No update, closeing.
